config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#index'

  get '/about' => 'static_pages#about'
  get '/whatwedo' => 'static_pages#whatwedo'
  get '/work' => 'static_pages#work'
  get '/contact' => 'static_pages#contact'

end

app/models/static_page.rb
class StaticPage < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	def index
	end
	def about
	end
	def whatwedo
	end
	def work
	end
	def contact
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>Portfolio</title>
	  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	  <%= csrf_meta_tags %>
	</head>
	<body>

		<%= yield %>

	</body>
</html>

app/views/static_pages/index.html.erb
<div class="loader">
	<div>

		<div class="center"></div>

		<div class="pattern">

			<div class="top">
				<div class="left"></div>
				<div class="angle-left">
						<div class="bar"></div>
				</div>
				<div class="middle"></div>
				<div class="angle-right">
					<div class="bar"></div>
				</div>
				<div class="right"></div>
			</div>

			<div class="bottom">
				<div class="left"></div>
				<div class="angle-left">
						<div class="bar"></div>
				</div>
				<div class="middle"></div>
				<div class="angle-right">
					<div class="bar"></div>
				</div>
				<div class="right"></div>

				<!-- <div class="enter enter-show">Enter</div> -->
			</div>

		</div>

		<div class="atom">
			<div>

				<div class="nucleus"></div>

				<div class="orbital">
					<div class="ellipse cyan">
				    <span class="moveX">
				       <div class="moveY"><span class="electron"></span></div>
				    </span>
					</div>
				</div>

				<div class="orbital">
					<div class="ellipse magenta">
				    <span class="moveX">
				       <div class="moveY"><span class="electron"></span></div>
				    </span>
					</div>
				</div>

				<div class="orbital">
					<div class="ellipse yellow">
				    <span class="moveX">
				       <div class="moveY"><span class="electron"></span></div>
				    </span>
					</div>
				</div>

			</div>
		</div>

	</div>
</div>

<header>

	<div class="atom">
		<div>

			<div class="nucleus"></div>

			<div class="orbital">
				<div class="ellipse cyan">
			    <span class="moveX">
			       <div class="moveY"><span class="electron"></span></div>
			    </span>
				</div>
			</div>

			<div class="orbital">
				<div class="ellipse magenta">
			    <span class="moveX">
			       <div class="moveY"><span class="electron"></span></div>
			    </span>
				</div>
			</div>

			<div class="orbital">
				<div class="ellipse yellow">
			    <span class="moveX">
			       <div class="moveY"><span class="electron"></span></div>
			    </span>
				</div>
			</div>

		</div>
	</div>

	<div class="main">

		<h1>Something-or-other Web Design</h1>
		<h3>Web design firm headquartered in Coeur d'Alene, Idaho.</h3>

		<span class="nav__button">
			<i class="licon-reorder"></i>
		</span>

		<nav class="navigation">

			<h3>Things</h3>
			<%= link_to 'Home', root_path %>
			<%= link_to 'About', about_path %>
			<%= link_to 'What we do', whatwedo_path %>
			<%= link_to 'Our work', work_path %>
			<%= link_to 'Contact', contact_path %>
			
		</nav>

	</div>

</header>